### ISSUE TITLE
自定义viewer-canvas 样式后, 预览图片显示位置异常

### ISSUE THREAD

**Issue by summerpen** [mirari/v-viewer#198]
自定义样式后,大屏预览图片,位置显示异常,
没有在容器的中央, `viewer-canvas` 下的img标签,`margin-top` `margin-left`异常
没有安装上一个容器计算
```html
<viewer
                v-if="item1.suffix != 'mp4' && item1.suffix != 'mov'"
                :images="item1.url"
                class="item"
                :options="options"
                ref="viewer"
              >
                <img :src="item1.url[0]" />
                
              </viewer>
```

```js
  created() {
    this.options = {
      // TODO: 111
      // container: '.componentCockpit',
      container: '#app',
      className: 'img-preview',
      title: false,
    }
  },
```
```less
.img-preview {
  &.viewer-transition {
    .viewer-canvas {
      height: auto;
      width: 1000px;
      background: rgba(0, 0, 0, 1) !important;
      opacity: 1;
      // left: 50%;
      // bottom: 104px;
      // right: none;
      // transform: translateX(-50%);
      // display: flex;
      // align-items: center;
      // justify-content: center;
      display: flex;
      align-items: center;
      justify-content: center;
      margin: 0 auto;
      vertical-align: middle;
      img {
        max-width: 800px !important;
      }
    }
    .viewer-footer {
      width: 1000px;
      background: rgba(0, 0, 0, 1);
      opacity: 0.8;
      left: 50%;
      transform: translateX(-50%);
    }
    .viewer-toolbar {
      padding: 32px 0;
      & > ul {
        display: flex;
        align-items: center;
        justify-content: center;
        height: 40px;
        margin: initial;
        padding: 0;
      }
      .viewer-zoom-in,
      .viewer-zoom-out,
      .viewer-one-to-one,
      .viewer-reset,
      .viewer-play.viewer-large,
      .viewer-flip-horizontal,
      .viewer-flip-vertical {
        display: none;
      }
    }
    .viewer-navbar {
      display: none;
    }
    .viewer-button {
      width: 34px;
      height: 34px;
      background: #44c0fe;
      border-radius: 50%;
      top: 16px;
      right: 16px;
      padding: 1px;
      z-index: 999;
    }
    .viewer-button::before {
      bottom: 7px;
      left: 7px;
      position: absolute;
    }
  }
}
```
